<a href="https://colab.research.google.com/github/joaombonaldo/PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


Python Lists

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays


In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.70776426, 0.0528728 , 0.98519398, 0.04370076],
       [0.0788949 , 0.08803555, 0.58657643, 0.15874812],
       [0.80502219, 0.13957265, 0.19355096, 0.35376797]])

Tensors


In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0873,  0.8056,  0.9118, -0.7542],
        [ 0.2153, -1.2356,  0.5052, -1.3823],
        [-1.6575, -0.1244, -1.0464, -0.8557]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7078, 0.0529, 0.9852, 0.0437],
        [0.0789, 0.0880, 0.5866, 0.1587],
        [0.8050, 0.1396, 0.1936, 0.3538]], dtype=torch.float64)